name: Ebay Scraper (Every 3 hrs)

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-bitcoin:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York # Set your local timezone if needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium pandas webdriver-manager fake-useragent requests beautifulsoup4

      - name: Run Selenium scrapers
        run: |
          python scrapper.py

      - name: Commit and Push updated CSV
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ebay_tech_deals.csv
          git commit -m "Updated Ebay scrapped data (every 3 hrs)"
          git push
